<?php
/**
 * @var \Magenest\Xero\Block\System\Config\Form\Information $block
 */
$userInfo = $block->getUserInfo();
?>
<div class="admin__page-section-item-content">
    <table class="admin__table-secondary">
        <tbody>
            <?php foreach ($userInfo as $label => $value) :?>
            <tr>
                <th><?php /* @escapeNotVerified */ echo $block->escapeHtml($label) ?></th>
                <th><?php /* @escapeNotVerified */ echo $block->escapeHtml($value) ?></th>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="item-xero"></div>

