<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>

<!--        <div class="stock available">-->
<!--            <span>-->
<!--                In stock-->
<!--            </span>-->
<!--        </div>-->
        <div class="stock available btn-cart ins"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
    <?php else : ?>
        <p class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml('bundle_prices') ?>
