<?php
namespace Magenest\Xero\Model\Config\Backend;

use Magenest\Xero\Model\Helper;
use Magento\Config\Model\Config\Backend\File;
use \Magento\Framework\Filesystem\DirectoryList;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\App\RequestInterface;

class XeroFile extends File
{
    const KEY_FILE_PATH = "xerokey";

    protected $fileExtension;

    protected $path;

    protected function _getAllowedExtensions()
    {
        return [$this->fileExtension];
    }

    public function afterSave()
    {
        /** @var Helper $xeroHelper */
        $xeroHelper = ObjectManager::getInstance()->get(Helper::class);
        if ($xeroHelper->getConfig('magenest_xero_config/xero_api/key_file_mode')) {
            /** @var DirectoryList $directoryList */
            $directoryList = ObjectManager::getInstance()->get(DirectoryList::class);
            /** @var RequestInterface $request */
            $request = ObjectManager::getInstance()->get(RequestInterface::class);
            $website = $request->getParam('website');
            if ($website) {
                $xeroHelper->setScope('websites');
                $xeroHelper->setScopeId($website);
            }

            $path = $directoryList->getPath('var').'/xerokey/';
            try {
                $content = trim(file_get_contents($path.$this->getValue()));
                $xeroHelper->saveConfig($this->path, $content);
            } catch (\Exception $exception) {
                $this->setValue("");
            }
        }
        return parent::afterSave(); // TODO: Change the autogenerated stub
    }

    public function getFileData()
    {
        $file = [];
        $value = $this->getValue();
        $tmpName = $this->_requestData->getTmpName($this->getPath());
        if ($tmpName) {
            $file['tmp_name'] = $tmpName;
            $file['name'] = $this->_requestData->getName($this->getPath());
        } elseif (!empty($value['tmp_name'])) {
            $file['tmp_name'] = $value['tmp_name'];
            $file['name'] = (isset($value['value']) && $value['value']) ? $value['value'] : $value['name'];
        }

        return $file;
    }
}