<?php
namespace Magenest\Xero\Block\System\Config\Form\Field;

use Magento\Config\Block\System\Config\Form\Field\File as BackendFile;
use Magento\Framework\App\RequestInterface;

class XeroFile extends BackendFile
{
    protected $fileExtension;

    protected $backendUrl;

    protected $_request;

    public function __construct(
        \Magento\Framework\Data\Form\Element\Factory $factoryElement,
        \Magento\Framework\Data\Form\Element\CollectionFactory $factoryCollection,
        \Magento\Framework\Escaper $escaper,
        \Magento\Backend\Model\UrlInterface $backendUrl,
        RequestInterface $request,
        array $data = [])
    {
        $this->backendUrl = $backendUrl;
        $this->_request = $request;
        parent::__construct($factoryElement, $factoryCollection, $escaper, $data);
    }

    public function serialize($attributes = [], $valueSeparator = '=', $fieldSeparator = ' ', $quote = '"')
    {
        $html = parent::serialize($attributes, $valueSeparator, $fieldSeparator, $quote); // TODO: Change the autogenerated stub
        return $html." accept='".$this->fileExtension."'";
    }

    protected function _getDeleteCheckbox()
    {
        $html = '<div>' . $this->getValue() . ' ';
        $html .= '<input type="hidden" name="' .
            parent::getName() .
            '[value]" value="' .
            $this->getValue() .
            '" />';
        if ($this->getValue()) {
            $html .= '<br>';
            $html .= $this->getDownloadLink();
        }
        $html .= '</div>';
        return $html;
    }

    protected function getDownloadLink()
    {
        $params = $this->_request->getParams();
        $params['file_extension'] = $this->fileExtension;
        return "<a onclick=\"setLocation('".$this->backendUrl->getUrl("xero/app/download", $params)."')\">Download</a>";
    }
}
