<?php

 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category

$category_id=(int)$category->getId();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$core_write = $resource->getConnection();
$tableName = $resource->getTableName('category_password');
$password="";
	$selectsql= "select * from `".$tableName."` where category_id='".$category_id."'";
	$category_password=$core_write->fetchAll($selectsql);
	if(count($category_password)>0){			
			foreach($category_password as $categorypassword)
				$password=$categorypassword['password'];			
	}

?>
<script>
jQuery('input[name=category_password]').val('<?php echo $password?>').trigger("change");
jQuery('input[name=category_password_changed]').val("1").hide().trigger("change");
</script>
  