<form id="subForm" action="https://gmail.us4.list-manage.com/subscribe/post?u=f2efff81332ff3296aab5fcf4&amp;id=a254e22c49" method="post" name="mc-embedded-subscribe-form">
    <div class="col-sm-11 col-xs-12">
        <p class="col-sm-6 col-xs-12"><label for="fieldName">Name</label> <input id="fieldName" style="color: #000;" name="FNAME" type="text" placeholder="Name" /></p>
        <p class="col-sm-6 col-xs-12"><label for="fieldEmail">Email</label> <input id="fieldEmail" style="color: #000;" name="EMAIL" required="" type="email" placeholder="Email" /></p>
    </div>
    <p class="col-sm-1"><button style="color: #000;" name="subscribe" type="submit"><i class="fas fa-long-arrow-right"></i></button></p>
</form>